name: Auto Translate Issues & PRs

on:
  issues:
    types: [opened, edited] # 当 Issue 被创建或编辑时触发
  pull_request:
    types: [opened, edited] # 当 Pull Request 被创建或编辑时触发

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      issues: write         # 允许 Action 在 Issues 上发表评论和添加标签
      pull-requests: write  # 允许 Action 在 Pull Requests 上发表评论和添加标签
    
    steps:
      - name: Auto Translate
        uses: usthe/issues-translate-action@v2.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label-name: 'auto-translated'
